# Generated by Django 4.1.4 on 2023-01-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=12, unique=True, verbose_name="تلفن"),
        ),
    ]
