# Generated by Django 4.1.3 on 2023-01-26 08:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0002_category_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "دسته بندی", "verbose_name_plural": "دسته بندی"},
        ),
    ]
