# Generated by Django 4.1.6 on 2023-02-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_alter_ordering_total_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordering",
            name="total_products",
            field=models.IntegerField(),
        ),
    ]
